spring:
  profiles.active: dev
---
spring:
   profiles: dev
server:  servlet:
    context-path: /dev
  port: 8889
---
spring:
   profiles: prod
server:
  servlet:
    context-path: /
  port: 8081